name: Discord Snapshot Collector

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 mins
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get install jq

      - name: Fetch Discord Data
        run: |

          echo "Fetching Discord invite..."

          curl -s \
            "https://discord.com/api/v10/invites/${INVITE}?with_counts=true" \
            > data.json

          cat data.json

          MEMBERS=$(jq '.approximate_member_count // 0' data.json)
          ONLINE=$(jq '.approximate_presence_count // 0' data.json)

          GUILD_ID_API=$(jq -r '.guild.id' data.json)
          GUILD_NAME=$(jq -r '.guild.name' data.json)
          GUILD_ICON=$(jq -r '.guild.icon' data.json)

          echo "Members: $MEMBERS"
          echo "Online: $ONLINE"

          echo "Updating guild info..."

          curl -X POST \
            "${SUPABASE_URL}/rest/v1/discord_guild" \
            -H "apikey: ${SUPABASE_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_KEY}" \
            -H "Content-Type: application/json" \
            -H "Prefer: resolution=merge-duplicates" \
            -d "{
              \"id\": \"${GUILD_ID_API}\",
              \"name\": \"${GUILD_NAME}\",
              \"icon\": \"${GUILD_ICON}\"
            }"

          echo "Inserting snapshot..."

          curl -X POST \
            "${SUPABASE_URL}/rest/v1/discord_snapshots" \
            -H "apikey: ${SUPABASE_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_KEY}" \
            -H "Content-Type: application/json" \
            -d "{
              \"guild_id\": \"${GUILD_ID_API}\",
              \"members\": $MEMBERS,
              \"online\": $ONLINE
            }"

    env:
      INVITE: ${{ secrets.INVITE }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
